[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    ignore::sklearn.exceptions.InconsistentVersionWarning
    ignore::pydantic.warnings.UnsupportedFieldAttributeWarning
    ignore::DeprecationWarning:websockets.*
